substitutions:
  name: "aquarium-atuomator"
  
esphome:
  name: aquarium-automator
#  name_add_mac_suffix: true
  
 # This will allow for (future) project identification,
 # configuration and updates.
  project:
    name: ddppddpp.aquarium-automator
    version: "1.0"


esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your_key_here"

ota:
  password: "your_OTA_password_here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aquarium-Automator"
    password: "SOME_PASSWORD_HERE"

captive_portal:

dallas:
  - pin: GPIO2
sensor:
  - platform: dallas
    #your address should be here - pls see https://esphome.io/components/sensor/dallas.html?highlight=dallas#dallas-getting-ids
    address: "your_address_here"
    name: "Aquarium Water Temperature"
    
switch:
  - platform: gpio
    name: "Relay1"
    pin: GPIO14
  - platform: gpio
    name: "Relay2"
    pin: GPIO12


    
